language: python

cache: pip

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  - pip install .

before_script:
  - pip install -r requirements_dev.txt

script:
  - pytest -x tests.py
  - black --check .

deploy:
  provider: pypi
  user: __token__
  password:
    secure: dKzDNB04a169cNNU61NelAyJsyvijjacuLhbZa7MspjfoqnDOz3b7UJrzrDKG7+rLnBYIO+TfKELT+vnxGuWCvL1tZPCX/ABLqNWBta2uSZmuBu8fPeRUB4au+DX1tziZZFMsVdTnD4CnFjt/c8bR9Njmeckg8VWJLHY2fUuCjn47QaK1Pls/DQVPSBR2s72k/MyagRU0T1phpDKXJSxciT25jRCRnloOPKixxTiHef3zFC7rgfDmo3Gxz7jftRMm0sreJsuFgWk/kKwoaTn1WZCy5/nO38OQ2K2qGf3s//HraEbummU9XHA10BwVtdAxy2MO0GzKf+/cktlFwI6+DhvuRWkGJKEJsdfu7FPRkTrEeNo8OmeXg/uNSwg8w2o24mwTpKLEaskdQdO1RVp09+fT4I5na6dW6aQ3Dn6xp/zl7XWn7DdUeOu+Go3KkwiN3uZYXM+QVYW8wM4zejOMXhmSZcaos5IMwWSavjDit/k/z9KnEcwdXwUoIkb5ndwxIGiVeoDdq6Syt8BHV0inGbh4IZs3m2FkHmd20/1bbD5bDumVAdMryFhA5ducX50Xp3enihpBfO0OaFhi9GPNx9uPBUZMWKwgWnBRhMY2ZyzZlYyx/bAhjG0qttGhxKSDEHPKzQCUcKmDhtAFkWm8FRbs63LNd7h9xvt03++ALw=
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
    branch: master
